os: linux
dist: trusty
sudo: false
language:
- c
- java

cache:
  directories:
  - $HOME/.m2

env:
  global:
    # COVERITY_SCAN_TOKEN
    - secure: "kLJXW7OvvVji1/ClZI3bVwBwqpAVF9pU3S5f8ZXcMsO/NI9BdMijg6uwF2XHGqiiwJ9a2bUncmcLZLrYQdsSCpUiryQm7Lv8oMDVCywV9ikmblsUKxfM582JlH2rf8ORnGMZ24nUcV8+1wtr4SQjTEnRlOn9lmv7RvLRNlBINdmVEulpNe6r9FXWJ6Nkd5wiWGniyNhff21sdt/8tbb/HUoBKV6UT9yP28pdgBpoa3X+jkSzgQYGmD/kHZ114wjE+f0xGhj89TUtBk4Lf22gdKOhj0x48Dzzucn7Z73BgKbm65APJ9PMIp73iCPWkbGkdY/suEqinGv5T8MTgdIP9O76WkvPjOwDZaM+1MZAIrW7raSuiz5Z5CV29Z9O6c8sSm4aW3j9dFpmhU2RQtEtfsplfivrNlAYB7LGZ02+rid0EBHKPL6R89wJUUlpYjhqVc8EfgFjKCIZQ6LtwBceAr+MN383XoDAUDbZ7AU4O4/ntuN+fEAwjvmQZPQtNW1Ekzp/naOaFSx0rePW0UsRO8RH6Tw9KrDjkjnBRe4zBWrNFD+5a0XwFdiBM05LDXPfFmBXDLwcO6kM6bVYjvdCz2dmRcdDUL3gjlcrw5TIthL+YZYiBQaCdOfA7nxHsuG0t3syDNmCi2mhb5WPEBrAj3g/EOR0vcvFpqQWmtm7UE0="

addons:
  apt:
    packages:
    - libaio-dev
  # https://scan.coverity.com/travis_ci
  coverity_scan:
    project:
      name: Apache ActiveMQ Artemis
      version: 2.1.0-SNAPSHOT
      description: Apache ActiveMQ Artemis has a proven non blocking architecture. It delivers outstanding performance.

    # notification_email: issues@activemq.apache.com

    # Commands to prepare for build_command
    build_command_prepend: ./prepare_for_build.sh

    # The command that will be added as an argument to "cov-build" to compile your project for analysis,
    build_command: ./build_for_analysis.sh

    # Pattern to match selecting branches that will run analysis. We recommend leaving this set to 'coverity_scan'.
    # Take care in resource usage, and consider the build frequency allowances per
    #   https://scan.coverity.com/faq#frequency
    branch_pattern: .*

# skip default build steps
script: []
