os: linux
dist: bionic
sudo: false
language: c
compiler:
- gcc
env:
  global:
    - "COVERITY_SCAN_PROJECT_NAME='Apache Qpid dispatch-router'"
    - "COVERITY_SCAN_NOTIFICATION_EMAIL='jdanek@redhat.com'"
    - "COVERITY_SCAN_BUILD_COMMAND='--fs-capture-search ./qpid-dispatch/ ./build_for_analysis.sh'"
    - "COVERITY_SCAN_BUILD_COMMAND_PREPEND='./prepare_for_build.sh'"
    - "COVERITY_SCAN_BRANCH_PATTERN='.*'"
    # COVERITY_SCAN_TOKEN
    - secure: Xhhx+2eaXWiTBVp3ls8boujQvImPo0xO/bG4j8TnQXdLYp49sW2PtbICEGi/rByC1ijzMPPrecL1DWQvmAWVCIFptmrUhTq9nnPYgO47YGAuTxYuA1/Tb+zyhIM2qPLZHwi4QNZ+l8xUrWLTkYIRgas/H8Hv04qiaql1CbNb6VugAb0DfOmIvJFIdBIxg83jN4q5ivzrK+r+5UtOpqeTJTetOxYJG9cutXZ/Tnnj/XxBgqEL5meIpzys1lty0tsoSyy0dmpgO5HCqIJiCFvpPrFKfLp2BU1+4iS8ZPbutg815Pb058J7bEmjW0cXMVPVaofTSrBK9PXmfz6dKL63CtgRz7n/JWos0ne9YqorhppIA0Qk3E/GPg8r4ZGWrF82GCqOhB9WhmkSdBO5wfwoSZz3EUQ2YGKzuDAkiLxQWUUXOuYZPm+h9y9UVsdpKZ8G7h4CoCNUgRrUwBHmf6qNUnRv6qZGcP7RedPe0fM329fcNhL0U1GdjA8Q1VBBSnQUK31Y72WVsQJl+4pwi0KVrCapOeMvmutio+JPdOF1SmN9W1BrfafK3qA6nWgpFane32NAK93EUG7dBXywbFXDf3AipS6Lh2limMggItwcnjlM55U9dy2rpE9ln4epuHqugZMB2A/rxpa8D6KWWa0SGMZf4LL1Cmzm8W8V9aA2rpU=
addons:
  apt:
    packages:
    - cmake
    - libssl-dev
    - libsasl2-dev
    - sasl2-bin
    - swig
    - python-dev
    - valgrind
    - ruby
    - ruby-dev
    - python3-dev
    - golang
    - lcov
    - libwebsockets-dev
script:
  - "bash travisci_build_coverity_scan.sh"
