os: linux
dist: bionic
sudo: false
language: c
compiler:
- gcc
env:
  global:
    - "COVERITY_SCAN_PROJECT_NAME='Apache Qpid dispatch-router'"
    - "COVERITY_SCAN_NOTIFICATION_EMAIL='jdanek@redhat.com'"
    - "COVERITY_SCAN_BUILD_COMMAND='./build_for_analysis.sh'"
    - "COVERITY_SCAN_BUILD_COMMAND_PREPEND='./prepare_for_build.sh'"
    - "COVERITY_SCAN_BRANCH_PATTERN='.*'"
    # COVERITY_SCAN_TOKEN
    - secure: "oi6WcJ1QweYqrlwTUAXe9174GcLTdxz+TQvYE6xYfAMAnLeNJVtxm6Wj/yXqdFHifu3VApjY1+it0057HFRqgCh5fQRENbtboKymXDLl0Nelci325ORGSJI/DKnWcv2lRe3jgvriPkJM2UDbJwPCaV0u7prxMHn/uyVnlzZx0qdEcifJIz5awKpW8qE7zwaBuN//IjLN9/H36KbOFzphh7+KHE+ocEq6vVrUOGYEAtWPLyseXv187FeDeKbq1ECzFVAKpg3pA7Occd4JORflf1+9Sw20sHbpn2IQrhxOB4hFKTw4kQkNjkhHJcusJhilDciv0fMr5pP+FWMm+bbvq4M70L8HNWTydgeO1CQjU99OJm9a2nTzW+HL/t/7jcTJtpGLRhUr+xnHppujENq7xOnGhxR2sVfObQHJSnGDPyBz6ZsSoFw8MscmKyp3wzErCJx75TS0rDtf9Tv2RnJTrz9tKd8pt1zX+nSaZOE3h9XwMrtlatp6HL7OlxCvL1+0ZpChuy6VnAcpblnBX9znebDj/GvkawojBJpsoSNiZvaxjDwB7WY1dk1GgK9ePoft0iHohBYDOW/QrVc3Z27mgLaJz7NG0YzRTpv5Nz/E4OaPBtZjQkgkmMt+F1+1rfzT7rcZMbL15wPXyi9FHZDummvLS25UeNKpBEgyvCr18pE="
addons:
  apt:
    packages:
    - cmake
    - libssl-dev
    - libsasl2-dev
    - sasl2-bin
    - swig
    - python-dev
    - valgrind
    - ruby
    - ruby-dev
    - python3-dev
    - golang
    - lcov
    - libwebsockets-dev
script:
  - "bash travisci_build_coverity_scan.sh"
