os: linux
dist: trusty
sudo: false
language:
- c
- cpp
- java
compiler:
- gcc
env:
  global:
    - "COVERITY_SCAN_PROJECT_NAME='Apache Qpid Proton'"
    - "COVERITY_SCAN_NOTIFICATION_EMAIL='jdanek@redhat.com'"
    - "COVERITY_SCAN_BUILD_COMMAND='--fs-capture-search ./ ./build_for_analysis.sh'"
    - "COVERITY_SCAN_BUILD_COMMAND_PREPEND='./prepare_for_build.sh'"
    - "COVERITY_SCAN_BRANCH_PATTERN='.*'"
    # COVERITY_SCAN_TOKEN
    - secure: qXvRPpRS9B/Mxi/5RgWzaQL+IRSGo1OkP1JjEyHXrwtNbBZ4RzrhLYjH91MaarqOl/nAqvsIzoWXphIgtKCinCmmONEKkQT8uLCeAAeqJ16EsIR0IXrMPY0jaLn1Lv7g32chrdZJCNCpTxJoWarEcb+EUjvuPORCsBmXkJPgNolleB6QM3LVg3Ay9g0KAVRVfIGnRA2uI2m53NCXYUZuesZr2uH10KXjYSiakpBz1/Z16OcRMme5cx43uydsCraLa5Qk8NZi2sjIaKqskIfGe19dTxwU5XiJdVR3hTsLzJ1xaNLyHuPLDkoKvKPojyw6NQCV/cOdIuewqUYeGJdkl4+5DdDNW3TU4pLxCbjDjj5IETYDJ3XphdMhS2ABhh7OeVxPggtjONO73kUPSOzeaxWfNyRDXMtb/uqiRj6yf+3bddA6/cFJqJ0fO8cl7zkynDLi2joSIT5Y4Fsq1ziJcm8BWVZI3mihXuA1CUgs19cvcCoxKU0R31cbeGdmYg7idVeSGNlCt42nZoqk0TFRkoo7GypHtXk3zDq0rh0B05yeprgp0UFz8GxYlMNs/jJeCP49Y/fpDCOKCCgX8L9h+QYOwXG3Ok7jK7YgMp5yxeaI5DFfw1FpwEo1BXOQTD9oXiLIGoBSrAY78zy6Ttp5pqiw2+D/9soismaXLsNN3N8=
cache:
  directories:
  - "$HOME/.m2"
addons:
  apt:
    packages:
    - cmake
    - libssl-dev
    - libsasl2-dev
    - sasl2-bin
    - swig
    - python-dev
    - valgrind
    - ruby
    - ruby-dev
    - python3-dev
    - golang
    - lcov
script:
  - "bash travisci_build_coverity_scan.sh"
