# https://docs.travis-ci.com/user/docker/
os: linux
dist: trusty
sudo: required
services:
- docker

cache:
  directories:
  - $HOME/.m2

env:
  global:
    # DOCKER_PASSWORD
    - secure: "dgdR5moMZsKyP/tS7ROYvpXC3gFw7negjnKJL8abFaslngshzYlEuCC6+O3qQpkMkt+fUJ+M5WxuhpSJtCUJwaWlWCyJsWSJp6wMvqeiC/PNM0MxY/vjUalJTqnxs1HZKxlo1ldnPOcLwSictMhOEf2tgh32pCdU+g3wnF4BOTzZbSKv5rGwzUxu7cBNHeea3pWptlVzL+Peep1gsyAHrXAhoXt+doXExwxUq+9HRsxOpd6A24T+n+Jt81+JreQWrpTS6gZJ3P1ktdscEgJDifQDt+yj/lfyLw1BjA8EQQMeknnWVkrpmclH/k20ICDqcnLmdZZAwW1GBzEg0bnYhaDPHZ5N9EvqB30kf4SOU9r6ooXBe86VgFMZji/Xnpd0aMC3gb3p8EP74InjjxZluvsT+q9E1KbWgae/SpgpzOiZ7nVgRilRG9pbRWmcVnqlpXNc0bZIG1BjvPwlpcI5QFpoxYx//7gXeKi4Q1SL5j4s9flJHjm5UThy7wfgI5e1vpxPjSgvPAnABHESY39X118Q2ihghfDljfOOiPMnySLu+QEL04qrQsJ4H/HYXPTvbO/rDS4pXSqOiZTaCqAZXWrecphkR2c30vSH6bl5J//f/ghKO/LTRN/XPv2PWFZ3evnsYHXPrKGT3jQrk6XSiRS3QvMtmV9HcmnCzLEjRzs="

script:
- ./build.sh

# https://sebest.github.io/post/using-travis-ci-to-build-docker-images/
after_success:
- docker login -u jdanekrh -p ${DOCKER_PASSWORD}
- ./push.sh
