#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

# https://docs.travis-ci.com/user/docker/
os: linux
dist: trusty
sudo: required

language: python
python: 3.5

services:
  - docker

addons:
  # https://docs.travis-ci.com/user/firefox/
  # https://muffinresearch.co.uk/using-the-latest-version-of-firefox-in-travis-ci/
  firefox: latest
  apt:
    sources:
      # http://blog.500tech.com/setting-up-travis-ci-to-run-tests-on-latest-google-chrome-version/
      - google-chrome
    packages:
      - google-chrome-stable

  # https://docs.travis-ci.com/user/sauce-connect/
  sauce_connect:
    username: "jdanekrh"
    access_key:
      secure: "Vn0Cl9WzYRpY45ia2s59yG5Xh+izphNjvYSEsmT21bkfgyUsnt8znnkfzMuStXTYmLGkGyK5DKbq9VndXjnnCbMMq8qgPOyQsx/iwWsYOJQUHJU5Q693H7+fR2RVdC4yDQl/XtKnBUgEiWhXhH4mgCgPl9vNd8MFoY9blZf7Kf90iAmRWJaBjAskHi3qdDtHPO4AExnpx55os6p4DpPeRww/HPEyBCxlegQ1rUmaapHGPAtJY+N17o/1LzGd/GRR2cNb8MMSQGDPvXaJ2Lc0FsAzhCtbJD3s7C/2XXUxzLlL/URb0Lyuz65eCuSiSm5hjVy2qOP1Xch+XDkDt71Y9cgQqR2BBejTDL1FT0DHHsLB/zk2585H00pyCOgSNhQmmmgULiV5x7ioAD0Op42N9Tg1oqEG+cFfgqlW566AvNVNz9g0ZGesR4mxd+/bowoOzvHt0aKb5wYBJDd+x4DqGdHAphJIDFNlpRqQvuy6FQWa6ZkkPON4+dZ/+Y3RmqoxKtTNiGkzh7oVyBgWgRSKiFaBMaTmF8QSU/ljJ2WSReIiiVqXevWPovqo+q5cSgWTzcrKCi0U5Dj8HufjpAAZw/7GkJXRpAiHWVynEdBePF56QPAPXlwc9J3BecNV4jC2dBTcTaKHhTtnF94LIZmLMK3dc2tj6THRsOr1PPrh8Bo="
    no_ssl_bump_domains: "127.0.0.1,localhost"

  # https://docs.travis-ci.com/user/browserstack/
  browserstack:
    username: "jiridanek1"
    access_key:
      secure: "GDwM3+9XHuRrkWPuSaUscDGiWfIlZTtnTXTv7qMi9KiMnbDStWuA67wX6e5yitywow1bIawz0UTEt2qTCEdr2iUDepvE+iz35UWlJ9HuZVsq93ZwL+JFfVYO3XmWJWXcPC8fyLWoqBq1N00cuQY9U28nIbU9tO1NjUPYNf/7rjYcMvN7mDIve4BkeBwgWz4WYhUmEMtLuVPeAVUGVWkVbJdkasPo5F4CgAdlhcUc6/2KyfZEa7lSTpKWIp6IvKuf8RVj45+0RY/5h9wwA0nrjF0+69nLlPTmUHg5/Ve2uoAVHz47B8WTo/HSkyz/1MGfzQZFUP7exlSrlniSZ+sa0InAcH2+UQY3wvqrHe5bXofj+On23s2ogtCw86FEBvsHBJe8f3FSIzNKH4DnwLXQ4tjqbxcG/u46DHo3zuykkCQnU/l1kPIO3JbY4lTngD1eFtKMXKAsXLxirCqX7Z+xHgF9ugrBxLrzFW/QB8Ao49KtL+q/Xyko0ObSKNiepxkmzAl33q4YweCyQRePnVwH7cn4Jf1soUhKzdeUuUNz0tkQ1lJiBqeOHoOCPXrLHgxAsf9U1yK9fMCEKfXvsi7/yCMwbywacLm7MHTUjb3f38vy7mzfBd99K5OD4eM7lK3X4y8Ahyc9ZznpWE86cjfDUVa9LLNPsTZF7uI3VLUs9oI="

# https://github.com/travis-ci/travis-web/blob/15dc5ff92184db7044f0ce3aa451e57aea58ee19/.travis.yml
env:
  global:
    - "SAUCELABS_USERNAME=jdanekrh"
    # SAUCELABS_API_KEY
    -  secure: "THx+Ckm3xsA4WD5wHZKg0vgC7oMCkJwgDIG7B1hpvt/7bwTehe64BQa4vRw/roJrJMNaIEEzKt17h/VmOvOdne1LNCfwvTUpKBbbLlwTLr8fvIbQgBDB0KS2fkhzjlm4//UP4rmIMjmKNGt2OLLxOcNHaK1NdpCh2bZv5awWs7Z0wIEmnrPSsWaJhqTsmg3XN522S+Mf96uDHdJm2jrV6V/OTlq01yn+VCIjr2+0b4HbLgXAgfZMUnCPr/kA0mkfzRx9zp7rgrVlCBVN7E3skGdJ363VNl9fagrXjuFuXjMeAEmmWhx2nFrAhBkqR36gBZbetYARgTOYj+SxeCj2XB9IvHaqikNPmhb1Sd0peWKFTMhrmKPQ87o2HOn7ta01gld4JH+3cF5y9y++xTaP7uE6RV9jzm0+Y32ZjIH97oHlPhvP95+jFbSOM843pRb+7pGUCuhtWnU8lcJdCCaG6qGR48BBgYtfSjX+11QiMm/ecfve8IHEqSDYeG7FbFVpXxdad45/Owi2ZJa3gRgsTJ6OiXXmVOu1grcQkUhZAdYploDmSpn8UqcwTMWIBq7jF8sCWLPf4kc6wk3XFiktlq4lOkV+BJ1wVSX0wpr9wO6UdI+XU+GXsIaUNDg0gcZyKovQtLBYkvk+imp2W8Aihv1Ri7z+zZXkW2uWzmM0vAE="
    - "BROWSERSTACK_USERNAME=jiridanek1"
    # BROWSERSTACK_ACCESS_KEY
    - secure: "b1y2W6NAP32pjVlscRPJ+qsn3VH9VaP+ARyNB8Mz8b/S/xi35qGh1gdzxL25sVqNGBjMizYxiDhTA67uX7C225BAvQvhpzcLD3LkmbrK56VDdnRkspVDkLKCWvPiKz0ibQgRzYWlfQqioKRIJdluZt5QLDfVeAuR0IYlFoxW3LbsWZzxqKJx7ySmfONfLQUD5M//thwanqy1vhvxaJHBXwO7jV61bomaZxDyqwo1uBkho1QWqrmJkyH4FLD+a7Lao3MAGtOMwxm6se+VJVNpFQk4VFN4ESNXJK6VD5xR2Z7c7TQiTrzZ4HbataUAvUriD381thAkxvXxac6aWOPemWsMWYKR5pIoxZZBF0ja6pnPgOFC6aw0BNh3uqPA+MCfguaWaIbFCP86ZHPbQie9sb6dtp+tQ5Bp7cR2Pg/cDN2FqY9rIyyUGD+BTGX+UiZW4p4RevZ5HdZm3vVrvYfDlY53pkWB+885pGoesDSkA7YQXhdRZYId4/QgXFgIPNfc9w7DPYn2NOvO9opl3l1xfrlusNoEnl4iP4EWFSWwl/q5rJTb6ZEuXQWa7xQoW/N8vwsKAlS9Z2EQHIvZcETqhJZoDI4hskfq7OcKWGSlztE/K9aPfpwAIXH52kBO9NWp3XVUyHvV9X910M8SNCNRxh3o2Aw/EOl33bJ4WpFRH7o="
    - "IMAGE_TAG=latest"
  matrix:
    - "CONSOLE=hawtio DRIVER=Chrome PLATFORM=any BROWSER_NAME=any VERSION=any"
    - "CONSOLE=hawtio DRIVER=Firefox PLATFORM=any BROWSER_NAME=firefox VERSION=any"
    - "CONSOLE=stand-alone DRIVER=Chrome PLATFORM=any BROWSER_NAME=any VERSION=any"
    - "CONSOLE=stand-alone DRIVER=Firefox PLATFORM=any BROWSER_NAME=firefox VERSION=any"
    - "CONSOLE=hawtio DRIVER=SauceLabs PLATFORM='Windows 8' BROWSER_NAME='internet explorer' VERSION='10.0'"
    - "CONSOLE=stand-alone DRIVER=SauceLabs PLATFORM='Windows 8' BROWSER_NAME='internet explorer' VERSION='10.0'"
    - "CONSOLE=hawtio DRIVER=BrowserStack PLATFORM='10' BROWSER_NAME='Edge' VERSION='14'"
    - "CONSOLE=stand-alone DRIVER=BrowserStack PLATFORM='10' BROWSER_NAME='Edge' VERSION='14'"

before_install:
  - bash ./start_docker_containers.sh

install:
  - git clone https://github.com/jdanekrh/dispatch-console-tests.git
  - pip install -r ./dispatch-console-tests/requirements.txt

script:
  - cd dispatch-console-tests && bash ./scripts/travis.sh

cache: pip
